### ISSUE TITLE
Post Removal Request - UW Homework Solutions

### ISSUE THREAD

**Issue by jsanders89** [sabotuer99/CS61b_hw4#1]
Hello,

My name is Jonathan and I work with the introductory computer science courses at the University of Washington. A post in this repository contains solution code to an assignment based on our Guitar Hero homework assignment.

https://github.com/sabotuer99/CS61b_hw4/blob/master/Homework4/src/synthesizer/GuitarString.java

This post's solution code is indexed by Google, enabling current students to easily find it and cheat on their assignments.

Would you please remove this post or make it private in order to help us enforce our academic policy?

By removing the post, you would be removing a tool that our students could use in academic misconduct.

Thank you,
Jonathan Sanders
Intro Support, Computer Science & Engineering
University of Washington
jsanders@cs.washington.edu

More info on our course: http://courses.cs.washington.edu/courses/cse142/15su/

**Comment by sabotuer99** [comment]
I created this solution while working through Berkeley's 61B course on data structures.  The original "Guitar Hero" assignment was created over ten years about by professors at Princeton http://introcs.cs.princeton.edu/java/assignments/guitar.html

Since you don't actually own the original content and this repository is the only evidence I have that I completed the work for this course (not an enrolled student so I don't get a transcript), I'm going to have to respectfully decline your request.

Does Washington not use Moss? https://theory.stanford.edu/~aiken/moss/
Or something similar... just an idea...
